spring:
  datasource:
    hikari:
      jdbc-url: 'jdbc:mysql://localhost:3306/booking-mysql?useSSL=false&allowPublicKeyRetrieval=true'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 1234@
